// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4849.BasicRobot;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveSpeedControllerLeft;
    public static SpeedController driveSpeedControllerRight;
    public static SpeedController driveSpeedControllerLazySusan;
    public static SpeedController dSCarm;
    public static RobotDrive driveRobotDrive;
    public static Counter LSE;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveSpeedControllerLeft = new Victor(1, 1);
	LiveWindow.addActuator("Drive", "Speed Controller Left", (Victor) driveSpeedControllerLeft);
        
        driveSpeedControllerRight = new Victor(1, 2);
	LiveWindow.addActuator("Drive", "Speed Controller Right", (Victor) driveSpeedControllerRight);
        
        driveSpeedControllerLazySusan = new Jaguar(3);
        LiveWindow.addActuator("Drive", "Speed Controller Lazy Susan", (Jaguar) driveSpeedControllerLazySusan);
        
        dSCarm = new Jaguar(4);
        LiveWindow.addActuator("Drive", "Speed Controller Arm Right", (Jaguar) dSCarm);
        
        
        driveRobotDrive = new RobotDrive(driveSpeedControllerLeft, driveSpeedControllerRight);
	
        driveRobotDrive.setSafetyEnabled(true);
        driveRobotDrive.setExpiration(0.1);
        driveRobotDrive.setSensitivity(0.5);
        driveRobotDrive.setMaxOutput(1.0);
        
        LSE = new Counter(1);
        LSE.setSamplesToAverage(1);
        LSE.setSemiPeriodMode(true);
       

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
